random_seed: 1
model: MTAD_GAT
dataset: penism
device: 'cuda'
batch_size: 32
val_fac: 0.1
eval_method: 'best_f1'
penism:
  window_size: 20
  epoch: 100
  normalize: 1 #这里的1我是想表示ture
  lr: 0.001
  train_data_path: data/penism/train_data_3.csv
  test_data_path: 'data/penism/test_data1_3.csv' 
  label_path: None
  horizon: 1
  n_features: 16
  out_dim: 16
  gru_n_layers: 1
  gru_hid_dim: 150
  forecast_n_layers: 3
  forecast_hid_dim: 150
  recon_n_layers: 1
  recon_hid_dim: 150
  dropout: 0.3
  alpha: 0.2
  use_gatv2: 1 #这里的1我是想表示ture
  gamma: 1
  kernel_size: 7