random_seed: 1
model: 'HSR'
dataset: SWAT
device: 'cuda'
batch_size: 32
val_fac: 0.1
eval_method: 'best_f1'
MSL:
  test_data_path: data/SWAT/test_data.csv
  val_data_path: None
  train_data_path: data/SWAT/train_data.csv
  label_path: data/SWAT/labels.csv
  window_size: 20
  step: 20
  epoch: 20
  learn_rate: 0.001
  dropout: 0.1
  input_dim: 0 #这个在读取数据的时候得到
  hidden_dim: [55]
  kernel_size: 3
  tcn_bias: 1
  radius: 10
  num_heads: 4
  num_transformer_layer: 2
SMD:
  test_data_path: data/SWAT/test_data.csv
  val_data_path: None
  train_data_path: data/SWAT/train_data.csv
  label_path: data/SWAT/labels.csv
  window_size: 20
  step: 20
  epoch: 20
  learn_rate: 0.001
  dropout: 0.1
  input_dim: 0 #这个在读取数据的时候得到
  hidden_dim: [ 38 ]
  kernel_size: 3
  tcn_bias: 1
  radius: 7
  num_heads: 4
  num_transformer_layer: 2
penism:
  test_data_path: data/SWAT/test_data.csv
  val_data_path: None
  train_data_path: data/SWAT/train_data.csv
  label_path: data/SWAT/labels.csv
  window_size: 20
  step: 20
  epoch: 20
  learn_rate: 0.0001
  dropout: 0.1
  input_dim: 0 #这个在读取数据的时候得到
  hidden_dim: [16]
  kernel_size: 3
  radius: 5
  tcn_bias: 1
  num_heads: 4
  num_transformer_layer: 2
SWAT:
    test_data_path: data/SWAT/test_data.csv
    val_data_path: None
    train_data_path: data/SWAT/train_data.csv
    label_path: data/SWAT/labels.csv
    window_size: 20
    step: 20
    epoch: 20
    learn_rate: 0.0001
    dropout: 0.1
    input_dim: 0 #这个在读取数据的时候得到
    hidden_dim: [ 51 ]
    kernel_size: 3
    tcn_bias: 1
    radius: 6
    num_heads: 4
    num_transformer_layer: 2
WADI:
  test_data_path: data/SWAT/test_data.csv
  val_data_path: None
  train_data_path: data/SWAT/train_data.csv
  label_path: data/SWAT/labels.csv
  window_size: 20
  step: 20
  epoch: 20
  learn_rate: 0.0001
  dropout: 0.1
  input_dim: 0 #这个在读取数据的时候得到
  hidden_dim: [127]
  kernel_size: 3
  tcn_bias: 1
  radius: 20
  num_heads: 4
  num_transformer_layer: 2
