random_seed: 1
model: HSR
dataset: MSL
device: 'cuda'
batch_size: 32
val_fac: 0.1
eval_method: 'best_f1'
MSL:
  alpha: 0.8
  test_data_path: data/MSL/D-14_test.npy
  val_data_path: None
  train_data_path: data/MSL/D-14_train.npy
  label_path: data/MSL/D-14_labels.npy
  window_size: 20
  step: 20
  epoch: 700
  learn_rate: 0.001
  dropout: 0.1
  input_dim: 0 #这个在读取数据的时候得到
  hidden_dim: [55]
  kernel_size: 3
  tcn_bias: 1
  radius: 10
  num_heads: 4
  num_transformer_layer: 2
SMD:
  alpha: 1
  test_data_path: data/MSL/D-14_test.npy
  val_data_path: None
  train_data_path: data/MSL/D-14_train.npy
  label_path: data/MSL/D-14_labels.npy
  window_size: 20
  step: 20
  epoch: 700
  learn_rate: 0.001
  dropout: 0.1
  input_dim: 0 #这个在读取数据的时候得到
  hidden_dim: [ 38 ]
  kernel_size: 3
  tcn_bias: 1
  radius: 10
  num_heads: 4
  num_transformer_layer: 2
penism:
  alpha: 1
  test_data_path: data/MSL/D-14_test.npy
  val_data_path: None
  train_data_path: data/MSL/D-14_train.npy
  label_path: data/MSL/D-14_labels.npy
  window_size: 20
  step: 20
  epoch: 700
  learn_rate: 0.0001
  dropout: 0.1
  input_dim: 0 #这个在读取数据的时候得到
  hidden_dim: [16]
  kernel_size: 3
  radius: 5
  tcn_bias: 1
  num_heads: 4
  num_transformer_layer: 2

  #下面加的就是我在改变decoder,使用drgru之后添加的参数，还是尝试阶段
  graph_head: 4
  graph_threshold: 0.5
  num_rnn_layers: 1
  feat_num: 16
  max_diffusion_step: 2
  GRU_n_dim: 64
SWAT:
    alpha: 1
    test_data_path: data/MSL/D-14_test.npy
    val_data_path: None
    train_data_path: data/MSL/D-14_train.npy
    label_path: data/MSL/D-14_labels.npy
    window_size: 20
    step: 20
    epoch: 700
    learn_rate: 0.0001
    dropout: 0.5
    input_dim: 0 #这个在读取数据的时候得到
    hidden_dim: [ 51 ]
    kernel_size: 3
    tcn_bias: 1
    radius: 10
    num_heads: 4
    num_transformer_layer: 2
    graph_head: 4
    graph_threshold: 0.7
    num_rnn_layers: 1
    feat_num: 51
    max_diffusion_step: 2
    GRU_n_dim: 64
WADI:
  alpha: 0.8
  test_data_path: data/MSL/D-14_test.npy
  val_data_path: None
  train_data_path: data/MSL/D-14_train.npy
  label_path: data/MSL/D-14_labels.npy
  window_size: 20
  step: 20
  epoch: 700
  learn_rate: 0.0001
  dropout: 0.1
  input_dim: 0 #这个在读取数据的时候得到
  hidden_dim: [127]
  kernel_size: 3
  tcn_bias: 1
  radius: 20
  num_heads: 4
  num_transformer_layer: 2

