random_seed: 1
model: SSHSR
dataset: penism
device: 'cuda'
batch_size: 32
eval_method: 'best_f1'

penism:
  epoch: 100
  learn_rate: 0.0001
  batch_size: 32
  train_data_path: data/penism/train_data_3.csv
  test_data_path: data/penism/test_data15_3.csv
  label_path: None
  window_size: 0 #这个要保持和base_length一致,所以后续在程序中再赋值
  base_length: 20
  fore_length: 20
  train_step: 1
  input_dim: 0 #这个是后面再读取数据的时候得到的
  hidden_dim: [16]
  tcn_bias: 1
  kernel_size: 3
  dropout: 0.1
  num_heads: 4
  alpha: 0.8
  radius: 5