random_seed: 1
model: 'TranAD'
dataset: MSL
device: 'cuda'
penism:
  train_batchsize: 32
  test_batchsize: 0
  val_batchsize: 0
  train_val_batchsize: 0
  dim_feedforward: 10
  test_data_path: data/MSL/T-13_test.npy
  val_data_path: "data/penism/val_data1.csv"
  train_data_path: data/MSL/T-13_train.npy
  feat: 0
  window_size: 20
  step: 1
  epoch: 100
  learn_rate: 0.001
  nhead: 4
  dropout: 0.1
  eval_method: 'best_f1'
MSL:
  train_batchsize: 32
  test_batchsize: 0
  val_batchsize: 0
  train_val_batchsize: 0
  dim_feedforward: 40
  test_data_path: data/MSL/T-13_test.npy
  val_data_path: none
  train_data_path: data/MSL/T-13_train.npy
  label_path: data/MSL/T-13_labels.npy
  feat: 0
  window_size: 20
  step: 1
  epoch: 100
  learn_rate: 0.001
  nhead: 4
  dropout: 0.1
  eval_method: 'best_f1'