random_seed: 1
model: 'COUTA'
dataset: 'penism'
device: 'cuda'
batch_size: 32
neg_batch_size: 6
val_fac: 0.1
val_data_path: "None"
window_size: 20
step: 1
learn_rate: 0.0001
dropout: 0.2

WADI:
  train_data_path: data/MSL/T-13_train.npy
  test_data_path: data/MSL/T-13_test.npy
  label_path: data/MSL/T-13_labels.npy
  input_dim: 0 #在读取数据时自动赋值
  hidden_dim: [100]
  kernel_size: 3
  tcn_bias: 1
  rep_hidden_dim: 100
  pretext_hidden: 100
  emb_dim: 100
  out_dim: 1
  max_cut_ratio: 0.5
  ss_type: 'Full'
  alpha: 0.5
SWAT:
    train_data_path: data/SWAT/train_data.csv
    test_data_path: data/SWAT/test_data.csv
    label_path: data/SWAT/labels.csv
    input_dim: 0 #在读取数据时自动赋值
    hidden_dim: [ 16 ]
    kernel_size: 3
    tcn_bias: 1
    rep_hidden_dim: 16
    pretext_hidden: 16
    emb_dim: 16
    out_dim: 1
    max_cut_ratio: 0.5
    ss_type: 'Full'
    alpha: 0.5
SMD:
  train_data_path: data/MSL/T-13_train.npy
  test_data_path: data/MSL/T-13_test.npy
  label_path: data/MSL/T-13_labels.npy
  input_dim: 0 #在读取数据时自动赋值
  hidden_dim: [ 16 ]
  kernel_size: 3
  tcn_bias: 1
  rep_hidden_dim: 16
  pretext_hidden: 16
  emb_dim: 16
  out_dim: 1
  max_cut_ratio: 0.5
  ss_type: 'Full'
  alpha: 0.5
MSL:
  train_data_path: data/MSL/C-1_train.npy
  test_data_path: data/MSL/C-1_test.npy
  label_path: data/MSL/C-1_labels.npy
  input_dim: 0 #在读取数据时自动赋值
  hidden_dim: [ 30 ]
  kernel_size: 3
  tcn_bias: 1
  rep_hidden_dim: 30
  pretext_hidden: 30
  emb_dim: 30
  out_dim: 1
  max_cut_ratio: 0.5
  ss_type: 'Full'
  alpha: 0.5
penism:
  epoch: 10
  train_data_path: data/penism/train_data.csv
  test_data_path: data/penism/test_data1.csv
  label_path: None
  input_dim: 0 #在读取数据时自动赋值
  hidden_dim: [ 16 ]
  kernel_size: 3
  tcn_bias: 1
  rep_hidden_dim: 16
  pretext_hidden: 16
  emb_dim: 16
  out_dim: 1
  max_cut_ratio: 0.5
  ss_type: 'Full'
  alpha: 0.5